env:
  LANG: C

common_task_template: &COMMON_TASK_TEMPLATE
  configure_script:
    - ./autogen.sh
    - ./configure --enable-all --enable-developer-warnings --enable-werror
  compile_script:
    - make
  test_script:
    - make check
  dist_script:
    - make dist
  source_artifacts:
    path: "*.xz"

alpine_task:
  name: Alpine
  matrix:
    - name: Alpine
      container:
        image: alpine:latest
  prepare_script:
    - apk update
    - apk add autoconf automake gcc g++ make libtool pkgconf xz
  << : *COMMON_TASK_TEMPLATE

debian_task:
  name: Debian
  matrix:
    - name: Debian 12
      container:
        image: debian:bookworm
    - name: Debian 11
      container:
        image: debian:bullseye
    - name: Debian 10
      container:
        image: debian:buster
  prepare_script:
    - apt-get update
    - apt-get install -y autoconf automake gcc g++ make libtool pkg-config
  << : *COMMON_TASK_TEMPLATE

fedora_task:
  name: Fedora
  matrix:
    - name: Fedora 37
      container:
        image: fedora:37
    - name: Fedora 36
      container:
        image: fedora:36
    - name: Fedora 35
      container:
        image: fedora:35
  prepare_script:
    - dnf install -y autoconf automake gcc g++ make libtool pkg-config xz
  << : *COMMON_TASK_TEMPLATE

freebsd_task:
  name: FreeBSD
  matrix:
    - name: FreeBSD 14
      freebsd_instance:
        image_family: freebsd-14-0-snap
    - name: FreeBSD 13
      freebsd_instance:
        image_family: freebsd-13-1
    - name: FreeBSD 12
      freebsd_instance:
        image_family: freebsd-12-3
  prepare_script:
    - pkg update -f
    - pkg install -y autoconf automake gmake libtool pkgconf
  << : *COMMON_TASK_TEMPLATE
  package_script:
    - make -C freebsd package
    - mv freebsd/work/pkg/*.pkg .
  binaries_artifacts:
    path: "*.pkg"
